name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Secret as top level env variable
        run: |
          export PASS_TEST_SECRET=$TEST_SECRET
          echo $PASS_TEST_SECRET
          echo $PASS_TEST_SECRET > file.txt
          cat file.txt
